const PreloadFonts = () => (
  <>
    <link
      rel="preload"
      href="/fonts/NotoSans/notosans-regular-webfont.woff2"
      as="font"
      type="font/ttf"
      crossOrigin=""
    />
    <link
      rel="preload"
      href="/fonts/NotoSans/notosans-bold-webfont.woff2"
      as="font"
      type="font/ttf"
      crossOrigin=""
    />
    <link
      rel="preload"
      href="/fonts/NotoSans/notosanssc-regular-webfont.woff2"
      as="font"
      type="font/ttf"
      crossOrigin=""
    />
    <link
      rel="preload"
      href="/fonts/NotoSans/notosanssc-bold-webfont.woff2"
      as="font"
      type="font/ttf"
      crossOrigin=""
    />
    <link
      rel="preload"
      href="/fonts/NotoSans/notosans-arabic-webfont.woff2"
      as="font"
      type="font/ttf"
      crossOrigin=""
    />
  </>
)

export default PreloadFonts
